### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by Y75QMO** [blockstack/secret-sharing#3]
def __init__(self, secret_int):
#This line is missing some parethesis. It should be
        ~~if not isinstance(secret_int, (int, long)) and secret_int >= 0:~~
        if not (isinstance(secret_int, (int, long)) and secret_int >= 0):
            raise ValueError("Secret must be a non-negative integer.")
        self._secret = secret_int

**Comment by shea256** [comment]
Thanks for pointing this out. This code is no longer in the library. Closing this issue.
