### ISSUE TITLE
Returning results of varying length

### ISSUE THREAD

**Issue by tomholub** [blockstack/secret-sharing#6]
Depending on the secret, the shares have different length. Based on spec it should always be the same length as the original secret.

Correct length:
<pre>
>>> SecretSharer.split_secret("205fcb5bd65d590c3b187a88bce077b9", 3, 5)
['1-26d92b6af22b9e72813806200d81f6d0', '2-6a71a977eeab9bb01a042934fd63299', '3-3fc998e17c9aaae5bc512fe283dd2b13', '4-5240a648eb3b71f2b14ace0da996e03f', '5-3e0c42cdcacd0ee1e08d1d14c103521d']
</pre>

Longer than expected:
<pre>
>>> SecretSharer.split_secret("c61b5432ae2436d8fc29ae38a205227c", 3, 5)
['1-63571f1a138698048c6cb5c743237939b0b1a021a5471a3c843eae8022a40db8', '2-66698be3fa70cdd2083df9367463f9c81193fadc6194c1494f264dc19b91d1ef', '3-937465db4bea1687373ca4d93c181abe8c26462e30d2bff5ce08bfd0cce6f21', '4-4bc04e87427012c7ce0e290ca13c10e5363cdcb529b05a5ead6d69327659e677', '5-2e04a460a38521f0180d15739cd3a773fa0363d3357e4c6740cce561d83436c8']
</pre>

**Comment by shea256** [comment]
Hi thanks for mentioning this @tomholub and please excuse the delay. I should have addressed your concerns in the latest branch I pushed. You can see the full discussion here: https://github.com/blockstack/secret-sharing/issues/16

**Comment by shea256** [comment]
Closing this now and we can continue the discussion in #16 if necessary.
